global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["192.168.0.103:9121"]

  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["192.168.0.103:9113"]
  - job_name: "mysql_sender"
    static_configs:
      - targets: ["192.168.1.103:8000"]
