global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["192.168.0.103:9121"]
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["192.168.0.103:9113"]
  - job_name: "mysql_sender"
    static_configs:
      - targets: ["192.168.1.10:8000"]
  - job_name: "mysql_sender2"
    static_configs:
      - targets: ["192.168.1.20:7000"]

  - job_name: "laravel_apps" # Tambahan untuk app1,2,3
    static_configs:
      - targets:
          - "192.168.0.103:8081/metrics"
