global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "laravel_app"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.0.103:9000"]

  - job_name: "redis_exporter"
    static_configs:
      - targets: ["192.168.0.103:9121"]

  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["192.168.0.103:9113"]
