global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["192.168.1.106:9121"]
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["192.168.1.106:9113"]

  - job_name: "mysql_sender"
    static_configs:
      - targets: ["192.168.1.10:8000"]
  - job_name: "mysql_sender2"
    static_configs:
      - targets: ["192.168.1.20:7000"]

  - job_name: "laravel_appsalb" # untuk app1,2,3
    static_configs:
      - targets:
          - "192.168.1.106:8081"

  - job_name: "laravel_apps_nonalb" # untuk app1,2,3
    static_configs:
      - targets:
          - "192.168.1.109:8081"
  - job_name: "redis_exporter_nonalb"
    static_configs:
      - targets: ["192.168.1.109:9121"]
  - job_name: "nginx_exporter_nonalb"
    static_configs:
      - targets: ["192.168.1.109:9113"]
