{
 "title": "Monitoring Web SmartCampus dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Total Apps flask", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AVG Memory ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes)\r\n\r\n",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "AVG CPU ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[5m])*10)",
     "legendFormat": "cpu"
    }
   ]
  },
  { "title": "Apps Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average response time ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_sum{exported_job=\"Laravel\"}[5m]) / rate(http_server_duration_milliseconds_count[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(redis_target_scrape_request_errors_total[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total_total[5m]))",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Duration Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_sum{job=\"laravel_apps\"}[1m]) / rate(http_server_duration_milliseconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes \r\n\r\n",
     "legendFormat": "mem"
    },
    {}
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])\r\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "changes(http_requests_total_total[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency apps",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_milliseconds_bucket{job=\"laravel_apps\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])*10",
     "legendFormat": "cpu"
    }
   ]
  }
 ]
}