{
 "title": "Monitoring Web SmartCampus dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Total Apps flask", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AVG Memory ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(process_virtual_memory_bytes)",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "AVG CPU ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(redis_cpu_sys_seconds_total{job=\"redis_exporter\"}[$__rate_interval]))",
     "legendFormat": "cpu"
    }
   ]
  },
  { "title": "Apps Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average response time ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[5m]) / rate(go_gc_duration_seconds_count[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(redis_target_scrape_request_errors_total{job=\"redis_exporter\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_http_requests_total\r\n", "legendFormat": "HTTP {{ status }}" }
   ]
  },
  {
   "title": "Duration Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(process_virtual_memory_bytes)",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job=\"nginx_exporter\", code=\"200\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency apps",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(redis_commands_latencies_usec_sum[5m]) / rate(redis_commands_latencies_usec_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(redis_cpu_sys_seconds_total{job=\"redis_exporter\"}[$__rate_interval]))",
     "legendFormat": "cpu"
    }
   ]
  }
 ]
}