{
 "title": "Monitoring Web SmartCampus dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "AVG apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes \r\n\r\n",
     "legendFormat": "mem"
    },
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])*10",
     "legendFormat": "cpu"
    }
   ]
  },
  { "title": "Apps Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Average response time ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_sum{exported_job=\"Laravel\"}[5m]) / rate(http_server_duration_milliseconds_count[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total_total{status=\"404\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total_total[5m]))",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Latency apps",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_milliseconds_bucket{job=\"laravel_appsalb\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "avg(redis_memory_used_bytes{job=\"redis_exporter\"})",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])\r\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "changes(http_requests_total_total[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_sum{job=\"laravel_appsalb\"}[1m]) / rate(http_server_duration_milliseconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n    rate(redis_cpu_sys_seconds_total[1m]) +\r\n    rate(redis_cpu_user_seconds_total[1m]) +\r\n    rate(redis_cpu_sys_children_seconds_total[1m]) +\r\n    rate(redis_cpu_user_children_seconds_total[1m]) +\r\n    rate(process_cpu_seconds_total[1m]) * 10\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}